-- 01_create_user.sql
-- Run as SYSTEM on FREEPDB1.

SET ECHO ON
SET SERVEROUTPUT ON

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'BLAZORD_OLIST';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[CREATE USER BLAZORD_OLIST IDENTIFIED BY BlazordOlist123 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS]';
    DBMS_OUTPUT.PUT_LINE('Created user BLAZORD_OLIST');
  ELSE
    DBMS_OUTPUT.PUT_LINE('User BLAZORD_OLIST already exists');
  END IF;
END;
/

GRANT CREATE SESSION TO BLAZORD_OLIST;
GRANT CREATE TABLE TO BLAZORD_OLIST;
GRANT CREATE VIEW TO BLAZORD_OLIST;
GRANT CREATE PROCEDURE TO BLAZORD_OLIST;
GRANT CREATE SEQUENCE TO BLAZORD_OLIST;
GRANT CREATE TRIGGER TO BLAZORD_OLIST;

SELECT username, account_status, default_tablespace
FROM dba_users
WHERE username = 'BLAZORD_OLIST';
